### PR TITLE
chore: upgrading `@ew-did-registry/*` deps 

### PR DESCRIPTION
**Pull request by artursudnik**

### CODE REVIEW

**Review by jrhender — COMMENTED** [review]
A couple points:
- I think it would be better to use the latest `alpha` version 0.8.1-alpha.1037.0 https://www.npmjs.com/package/@ew-did-registry/jwt/v/0.8.1-alpha.1037.0
- I think the `didStoreCluster` version could also be updated (it is further down in the package.json)

**Review by jrhender — APPROVED** [review]
Looks good to me. I took a quick look at the recent commits in ew-did-registry and I don't see anything that would cause issues: https://github.com/energywebfoundation/ew-did-registry/commits/development
@nichonien let us know if any risks with this upgrade come to mind for you.

**Comment by nichonien** [comment]
> Looks good to me. I took a quick look at the recent commits in ew-did-registry and I don't see anything that would cause issues: https://github.com/energywebfoundation/ew-did-registry/commits/development
> @nichonien let us know if any risks with this upgrade come to mind for you.

@jrhender @artursudnik We still rely on older version of `@ew-did-registry/did-ipfs-store` i.e. `0.7.1-alpha.816.0` in 
1. `passport-did-auth` - https://github.com/energywebfoundation/passport-did-auth/blob/7bc46205872e090d96fe0d7254f359bc81365726/package.json#L51
2. `ew-credentials` - https://github.com/energywebfoundation/ew-credentials/blob/2867b93bda7264c7b36ea89b868a2b151ff34dd2/packages/vc-verification/package.json#L44
3. `iam-client-lib` - https://github.com/energywebfoundation/iam-client-lib/blob/278f4a6f95d01a63c6e6d3fe3086d27823df0a65/package.json#L78

IMO, it would be better to upgrade it everywhere and then do it in `ssi-hub`, what do you say?

**Comment by jrhender** [comment]
@nichonien 

> @jrhender @artursudnik We still rely on older version of @ew-did-registry/did-ipfs-store i.e. 0.7.1-alpha.816.0 in

Thanks for bringing this up. However, we are also still relying on the only version of `did-ipfs-store` here: https://github.com/energywebfoundation/ssi-hub/blob/develop/package.json#L99 in order to maintain compatibility with iam-client-lib's credential publishing. Does this alleviate your concerns?

**Comment by nichonien** [comment]
> @nichonien
> 
> > @jrhender @artursudnik We still rely on older version of @ew-did-registry/did-ipfs-store i.e. 0.7.1-alpha.816.0 in
> 
> Thanks for bringing this up. However, we are also still relying on the only version of `did-ipfs-store` here: https://github.com/energywebfoundation/ssi-hub/blob/develop/package.json#L99 in order to maintain compatibility with iam-client-lib's credential publishing. Does this alleviate your concerns?

We can merge it then. Thanks @jrhender!

**Review by nichonien — APPROVED** [review]

**Pull request merged**
