### PR TITLE
2.11 release to production

### PR DESCRIPTION
**Pull request by jrhender**
Release of 2.11.1 and 2.11 to production. See changelog for details.

Test results of this version are here: https://github.com/energywebfoundation/switchboard-bdd/blob/master/src/ssi-hub/acceptance-plan/test-results-16112022/claimsModule.md

### CODE REVIEW

**Review by nichonien — APPROVED** [review]

**Review by JGiter — COMMENTED** [review]
May be its ok, but wouldn't be safer dev -> staging -> production?

**Comment by jrhender** [comment]
> May be its ok, but wouldn't be safer dev -> staging -> production?

@JGiter `staging` has a code freeze at the moment due to Project Edge and Symphony

**Comment by JGiter** [comment]
Ah, Ok

**Review by JGiter — APPROVED** [review]

**Comment by jrhender** [comment]
Closing and will recreate directly from the 2.11 tag

**Pull request merged**
