### PR TITLE
update passport-did-auth

### PR DESCRIPTION
**Pull request by JGiter**

### CODE REVIEW

**Review by Harasz — APPROVED** [review]

**Review by jrhender — CHANGES_REQUESTED** [review]
@JGiter Can we hold off on merging this until the staking launch is done (should be done by Friday)?

**Comment by JGiter** [comment]
> @JGiter Can we hold off on merging this until the staking launch is done (should be done by Friday)?

sure

**Comment by Harasz** [comment]
@jrhender Can we proceed?

**Review by jrhender — APPROVED** [review]
Yes, I think it should be okay

**Pull request merged**
